#!/bin/bash
#some code was generated by ai, the rest is either from my brain, Ubuntu Unleashed book, or from the checklist
if (( EUID != 0 )); then
    echo "Error: This script must be run as root or with sudo." >&2
    exit 1
fi

clear
echo "Success: Running with root privileges."

echo "Prerequisites"
echo "Make sure APT repos are set up before continuing the script."
echo "Copy paste the list of all users from the README (without passwords) into /home/$SUDO_USER/users.txt"
echo "Also copy paste the list of admins from the README (without passwords and without yourself into /home/$SUDO_USER/admins.txt"

read -p "Press [Enter] to continue running the script..."

read -p "Are the forensics questions answered/answerable? (y/n): " answer

case "$forensics" in
    [yY] | [yY][eE][sS] )
        echo "Proceeding..."
        ;;
    [nN] | [nN][oO] )
        echo "Be careful while running the script to not break anything."
        ;;
    * )
        echo "Invalid response."
        ;;
esac

read -p "Does the README specify to not update packages? (y/n): " answer

case "$pkg_update" in
    [yY] | [yY][eE][sS] )
        echo "Update Manually"
        ;;
    [nN] | [nN][oO] )
        echo "Proceeding..."
        apt update -y > /dev/null
        apt list --upgradable $SUDO_USER/upgraded_pkgs.txt
        apt upgrade -y > /dev/null
        echo "Check for packages installed via Mint Store and uninstall anything that is not approved."
        ;;
    * )
        echo "Invalid response."
        ;;
esac
apt install ufw stacer libpam-pwquality -y > /dev/null
ufw enable > /dev/null
passwd -l root

#PAM Stuff

touch /usr/share/pam-configs/faillock
touch /usr/share/pam-configs/faillock_notify
touch /usr/share/pam-configs/faillock_reset
echo "Name: Enforce failed login attempt counter
Default: no
Priority: 0
Auth-Type: Primary
Auth:
[default=die] pam_faillock.so authfail
sufficient pam_faillock.so authsucc" > /usr/share/pam-configs/faillock

echo "Name: Notify on failed login attempts
Default: no
Priority: 1024
Auth-Type: Primary
Auth:
requisite pam_faillock.so preauth" > /usr/share/pam-configs/faillock_notify

echo "Name: Reset lockout on success
Default: no
Priority: 0
Auth-Type: Additional
Auth:
required pam_faillock.so authsucc" > /usr/share/pam-configs/faillock_reset
pam-auth-update --enable Enforce failed login attempt counter
pam-auth-update --enable Notify on failed login attempts
pam-auth-update --enable Reset lockout on success

#Users/Groups
cd /home/$SUDO_USER
groupmems -g sudo -l > machineadmins.txt
sort admins.txt > admins.txt
sort machineadmins.txt > machineadmins.txt
diff machineadmins.txt admins.txt > maybebadadmins.txt
read -p "Check maybebadadmins.txt and Press [Enter] to demote them, but you can delete manually if you need to."
for admin in $(cat maybebadadmins.txt); do
    echo "Demoting user: $admin"
    deluser "$user" sudo
done

awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd > /home/$SUDO_USER/machineusers.txt
sort users.txt > users.txt
sort machineusers.txt > machineusers.txt
diff machineusers.txt users.txt > maybebadusers.txt
read -p "Check maybebadusers.txt and Press [Enter] to delete them, but you can delete manually if you need to."
for user in $(cat maybebadusers.txt); do
    echo "Removing user: $user"
    userdel -r "$user"
done

read -p "Does the README need extra user management? If so, mkdir group, create txt named group.txt and user.txt, self explanatory. User is mkdir user, user.txt. Tupe G for group, U for users"

case "$usrmng" in
    [gG] | [gG][rR][oO][uU][pP]  )
        cd group
        $groupmake=(cat group.txt)
        echo "Making group $groupmake"
        groupadd $groupmake
        for user in $(cat user.txt); do usermod -aG $groupmake "$user"; done
        ;;
    [uU] | [uU][sS][eE][rR] )
        cd user
        $usermake=(cat user.txt)
        echo "Making user $usermake"
        useradd -m -s /bin/nologin $usermake
        echo "User $usermake made."
        ;;
    * )
        echo "Invalid response."
        ;;

for user in $(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd); do
    chage -M 90 "$user"
done
read -p "All *unhidden* users' max password age were set to 90, but there could be hidden users, check for those now."

#Security Configs

LOGIN_DEFS="/etc/login.defs"

# Backup original file first
cp "$LOGIN_DEFS" "${LOGIN_DEFS}.bak"

# Function to update or add a parameter in login.defs
set_login_def() {
  local key="$1"
  local value="$2"

  # Check if the key exists (ignoring commented lines)
  if grep -qE "^\s*${key}\s+" "$LOGIN_DEFS"; then
    # Replace existing value
    sed -i -E "s/^\s*${key}\s+.*/${key}   ${value}/" "$LOGIN_DEFS"
  else
    # Append if it doesn't exist
    echo "${key}   ${value}" >> "$LOGIN_DEFS"
  fi
}

set_login_def "PASS_MAX_DAYS" "60"
set_login_def "PASS_MIN_DAYS" "20"
set_login_def "PASS_WARN_AGE" "7"
echo "/etc/login.defs updated successfully."
