#!/bin/bash
#if a section of code has code gen by ai, that means that code was generated by ai, usually claude or gemini
#code gen by ai
if (( EUID != 0 )); then
    echo "Error: This script must be run as root or with sudo." >&2
    exit 1
fi

echo "Success: Running with root privileges."
#end code gen

echo "Make sure APT repos are set up before continuing the script."
#code gen#
read -p "Press [Enter] to continue..."
#end code gen
